### ISSUE TITLE
how to use express without view engine?

### ISSUE THREAD

**Issue by THCloud** [ganarajpr/express-angular#6]
Hi,
I'm a new learner and trying to do something with angular and express, just like this repo.
But a small question:
how to use express without view engine? I mean, I wanna use html files in angular's route

that means like this:

$routeProvider.when('/', { templateUrl: '../../  .html' .... });

I have saw your angular's route.js.   Your templateUrl is a path that matched with express' route, right?
And express render the html files to browser

But I'm quite uncomfortable with it. I don't think this is a good solution to a single page web app.

Any solutions ?

**Comment by ganarajpr** [comment]
You need to look at `express.static` which helps you to expose a complete folder through the server. 

Here is the documetation for it : 
http://expressjs.com/en/starter/static-files.html

**Comment by THCloud** [comment]
Hey...
That's not what I want....
If used express.static, your file will expose by input the path in browser.. Then angular here makes no sense anymore.

**Comment by THCloud** [comment]
Any other solutions?
